### ISSUE TITLE
compact syntax for insert

### ISSUE THREAD

**Issue by guntiso** [mrumkovskis/tresql#24]
```
+some_table {...} some_other_table { col1 c1_alias, col2, 2*2 col_x }
```
where `{...}` (or similar) could be a shortcut for "all column names as returned by the query to the right", i.e.
```sql
insert into some_table(c1_alias, col2, col_x)
  select col1 c1_alias, col2, 2*2 col_x
   from some_other_table
```
Or support some other syntax where insertable column list is implied or paired with value expression like in sql `update`.

**Comment by mrumkovskis** [comment]
👍

**Comment by mrumkovskis** [comment]
Implemented as

+some_table { * } some_other_table { col1 c1_alias, col2, 2*2 col_x }
