### ISSUE TITLE
tresql cols minus not except

### ISSUE THREAD

**Issue by guntiso** [mrumkovskis/tresql#25]
```
joins: >-
  rēķins         (# doctype, numurs,  summa, piesaistītā_summa) {
    norekini_rekins doc
    [klients_id = :klients_id & datums_izraksts < :datums? &
     numurs !%~% 'K']
    {'rēķins', numurs, aprekinats,
     (norekini_sasaiste [rēķina_id             = doc.id] {sum(sasaistes_summa)}) -
     (norekini_sasaiste [kredītrēķina_id       = doc.id] {sum(sasaistes_summa)})
    }
  },
```
produces "`except`", bet "`-`" is expected. Hints:
- in column clause
- in parentheses
- single column
- aggregate function result

**Comment by mrumkovskis** [comment]
Proposed solution is to cast query operand, so tresql would now that the value is scalar:

`(norekini_sasaiste [rēķina_id             = doc.id] {sum(sasaistes_summa)})::int -
  (norekini_sasaiste [kredītrēķina_id       = doc.id] {sum(sasaistes_summa)})::int
`
