### ISSUE TITLE
tresql sql function cast to query

### ISSUE THREAD

**Issue by guntiso** [mrumkovskis/tresql#26]
Enable sql function result interpretation as query. Maybe cast to special `table` type with columns or somehow use CTE syntax. Example of unsupported sql:
```sql
select sum(n::int) from unnest(string_to_array('1, 2, 3', ', ')) n
```

**Comment by mrumkovskis** [comment]
Can be written in tresql starting with empty square brackets:

[]unnest(string_to_array('1,` 2, 3', ', ')) n {sum(n::int)}
