### ISSUE TITLE
Problems with arithmetic operation

### ISSUE THREAD

**Issue by Janqis** [mrumkovskis/tresql#38]
- Query.build("data(#){ {1 a } },atad(#){ {2 b }} {a * b / 6 c}")
14.04.2021 11:32:15.195 DEBUG org.wabase.tresql.tresql  - data(#){ {1 a } },atad(#){ {2 b }} {**a * b / 6** c}
java.util.NoSuchElementException: key not found: b

- Query.build("data(#){ {1 a } },atad(#){ {2 b }} { (1 / 6) * a * b  c}")
14.04.2021 11:37:15.372 DEBUG org.wabase.tresql.tresql  - data(#){ {1 a } },atad(#){ {2 b }} { **(1 / 6) * a * b**  c}
res3: org.tresql.Expr = with data as (select 1 as a), atad as (select 2 as b) select (1 / 6) * a * b as c

**Comment by mrumkovskis** [comment]
[Resolved in commit](../commit/e9dc65242a17b926ec0030b0e6d9fb25bac1bf97)
In hsqldb dialect generates sql like this:
`with data as (select 1 a from (values(0))), atad as (select 2 b from (values(0))) select a * b / 6 c from (values(0))`
