### ISSUE TITLE
re. column conversion to lowercase

### ISSUE THREAD

**Issue by emikhelo** [mrumkovskis/tresql#9]
My suggestion is not to convert all selected columns to lowercase, but only to make the _default_ case lowercase when all columns from table are selected.

I.e. query with just a table name should produce columns in lowercase.
But otherwise columns, esp. with case-sensitive names should not be converted.

I.e. in the following query I have case-sensitive column name nodeId, because is it mapped directly to Javascript object, which uses case-sensitive naming of course:

ipasums [id = :nodeId] 
{
  adrese_teksts text,  
  |pum [pum.ipa_id = :nodeId] {
    id nodeId,
    ("PUM " || pum_nr) text,
    |poz [pum_id = :1(1)] { 
       id nodeId, 
       ("POZ " || poz_nr) text,
       |psnorma [poz_id = :1(1)] {
          id nodeId,
          ("PS/Norma " || ps_numurs) text,
          "true" leaf
       } children
    } children
  } children
}

**Comment by mrumkovskis** [comment]
Resolved:

`dept[10]{dname Dname}`

produces:
```scala
List(Map("Dname" -> "ACCOUNTING"))
```
